[tool.poetry]
name = "plotter"
version = "0.1.0"
description = ""
authors = ["wilmer05 <wilmer0593@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
matplotlib = "^3.2.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
